on:
  push:
    branches: [master]
jobs:
  k6_performance_test:
    name: k6 test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Local k6 test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: test/check.js